Name: Build

on:
  check_suite:
    types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build dApp in a Docker Container
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag pizza-wallet:$(date +%s)
