name: Test

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Docker Build
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: apt install --no-cache git openssh && yarn install
      - name: Test
        run: yarn run test
