name: Test

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Docker Build
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: docker build -f Dockerfile.test .
